version: '3.5'
services:
 web_dev:
  build: .
  ports:
   - "4000:4000"
  volumes:
   - .:/python-flask/modules/app
  environment:
   - ENV=development
   - PORT=4000
   - DB=mongodb://mongodb:27017/todoDev
networks:
 default:
  name: web_dev